name: Build and publish Docker image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env:
  IMAGE_NAME: saho-portfolio

jobs:

  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest
      
    - name: Push the image to GitHub Packages
      run: docker push ghcr.io/sahodev/$IMAGE_NAME:latest
